### PR TITLE
Add note export functionality to vivaldi-notes script

### PR DESCRIPTION
**Pull request by fnkabit**
Feature https://github.com/pbek/QOwnNotes/issues/1165

### CODE REVIEW

**Comment by pbek** [comment]
I merged your PR, but you need to bump the version number of your script or else current users can't update.

**Comment by fnkabit** [comment]
> I merged your PR, but you need to bump the version number of your script or else current users can't update.

Thank you ! I wasn't aware; will bump version number right now.

**Comment by pbek** [comment]
I see you are using the new NoteSubFolder class? I'm about to release 20.11.0 now, please also update your `minAppVersion` to that version.

**Comment by pbek** [comment]
> I see you are using the new NoteSubFolder class? I'm about to release 20.11.0 with it now, please also update your `minAppVersion` to that version.

I bumped your minAppVersion and released 20.11.0.

**Pull request merged**
