### PR TITLE
New asynchronous version of render-plantuml

### PR DESCRIPTION
**Pull request by Beurt**
Now PlantUML runs in the background and let users continue typing while the diagram is generated

Other new features:

- the default work dir is the QON cache directory (default is not `/tmp` anymore)
- a new option is introduced to generate the diagrams in SVG (default is still PNG)
- a rudimentary cache system is introduced: PlantUML is launched only if the (md5 of the) text describing the diagram is changed
- the script handles files with native scripting methods (and not with node.js as before, thus the node.js dependency is dropped) 

In some very rare cases, the diagram in the preview may not be refreshed properly. If so you can add a trailing space in your PlantUML graph to force a new refresh.

### CODE REVIEW

**Comment by Beurt** [comment]
Sorry, I don't understand why the (very old) changes to the script Critic Markup are embedded in this PR all over again??? These old changes where already merged (15 month ago), so I don't get why Github is not letting me doing the PR without these.

**Comment by pbek** [comment]
Maybe you didn't pulled the latest changes from this repository into your fork of it?

**Comment by pbek** [comment]
So are you updating two scripts with this PR on purpose?

**Comment by Beurt** [comment]
Sorry Github lost me on this one.

Days ago, I made a **new** fork of the master of https://github.com/qownnotes/scripts. I used that fork to develop the new version of render-plantUML.

Then, I just made the PR from this modified fork. I really don't understand why Github includes modifications on two scripts instead of one in this PR.

Above all, what I don't understand is that the modifications of Critic Markup (the other script) were already merged months ago in your master. So the files of Critic Markup in https://github.com/qownnotes/scripts are exactly the same than in the fork I made (of course, since I forked the master).

So, in fact there is only changes to one script (render-plantuml), an no change at all for the second one (files are the same in both branches, yours and mine).

**Comment by Beurt** [comment]
I tried to merge your master in my master and it seems OK. Again, I don't get why I had to do that since my fork was made on the up to date master.

Sorry for the inconvenience. Everything should be OK. now.

**Pull request merged**
