### PR TITLE
Update outline-numbering.qml

### PR DESCRIPTION
**Pull request by DutchPete**
Fixed numbering that was incorrect for deeper level headings.

### CODE REVIEW

**Comment by pbek** [comment]
You are changing almost every line of code in that pull request. I guess @jerksen would need to review those changes.
And don't forget about the version number bump, https://github.com/qownnotes/scripts?tab=readme-ov-file#editing-an-existing-script-in-the-github-web-interface.

**Comment by DutchPete** [comment]
@Jerksen wrote that code 4 years ago, and since I originally pointed out the bug in the issues list he has not replied, so I guess he has abandoned the script.

So, what does that mean in practice for the revised script I submitted?

**Comment by DutchPete** [comment]
Remember, I don't know anything about this stuff, so you'll get basic questions.

How do I bump the number? Please give me a link to the Github page to do that.

**Comment by pbek** [comment]
You are doing good. 😊
I mentioned the version number in https://github.com/qownnotes/scripts/issues/250#issuecomment-2550568062.

**Comment by pbek** [comment]
But since you already have two open pull requests, be sure you are doing the commit to change the version in your `patch-2` branch! That's here: https://github.com/DutchPete/scripts/tree/patch-2

**Comment by DutchPete** [comment]
I assume the ball is in your court now: approval.

**Comment by pbek** [comment]
Approval of what?

**Comment by DutchPete** [comment]
This, as shown above:

image

**Comment by pbek** [comment]
But you are not done yet, see https://github.com/qownnotes/scripts/pull/252#issuecomment-2551297815.

**Comment by DutchPete** [comment]
So, please provide a link to the page where I can bump the version number.
Note: I am asking basic questions because I am completely unfamiliar with this. So, please answer questions as if I am a 5-year old.

**Comment by pbek** [comment]
The version number is always in the `info.json` next to the script.
In this case: https://github.com/DutchPete/scripts/blob/patch-2/outline-numbering/info.json#L7

**Comment by DutchPete** [comment]
I upped the version number and committed the change.

**Comment by DutchPete** [comment]
So, what is the next step with the PR being a WIP?

252-PR-wip

**Comment by pbek** [comment]
None. The PR was already merged.

**Pull request merged**
