### PR TITLE
Update mermaid HTML Character to normal characters

### LINKED ISSUE #144: Mermaid script isn't working
I'm not sure why this is not working. The code seems fine. There's very little output/logging on this one.

#### Script name
Mermaid

#### Script authors
[pkeb](https://github.com/qownnotes/scripts/commits?author=dohliam)

#### Expected behaviour
It shows a diagram...

#### Actual behaviour
It doesn't show a diagram :)

#### Steps to reproduce
Install qownnotes on debian 11.1
Install mermaid script via repository
Add following text to note:
```
```mermaid
sequenceDiagram
    actor User
    actor webview as Browser/Webview
    participant GW as Configuration app
    participant GWS as Windows Service
    participant API as Nintex Gateway API (NWC)
    
    participant NWC
    User->>+GW: Type URL
    note right of GW: This happens while you type
    GW->>+API: Validate URL (anonymous call)
    API-->>-GW: Valid/Invalid response
    alt Valid response received
        GW->>GW: Enable "start gateway" button
    end
    GW->>-User: 
    User->>+GW: Press "start gateway"
    GW->>+webview: Open Webview to Authenticate URL
    note over GW: Simplified authentication request/response
    webview->>+NWC: Get Login page
    NWC-->>-webview: Login page
    User->>webview: Enter credentials
    webview->>+NWC: Validate Credentials
    NWC-->>-webview: Authentication Token
    webview-->>-GW: Authentication token
    GW->>GW: Store authentication token
    GW->>GWS: Start Windows Service
    GW-->>-User: Show current status
```

```

#### Output from the debug section in the settings dialog
None.

#### Relevant log output in the Log panel
None

### PR DESCRIPTION
**Pull request by cyclops1982**
There must be a cleaner way to do this..

For now this works.

Fixes #144

### CODE REVIEW

**Comment by pbek** [comment]
Can you please also bump the version number in the `info.json` so users will get an update notification and add yourself as author (if you don't already are).

**Comment by cyclops1982** [comment]
Done.

**Comment by pbek** [comment]
Thank you!

**Comment by pbek** [comment]
Btw, the issue was closed because you wrote `Fixes #144` 😉

**Comment by cyclops1982** [comment]
@pbek Yes, i know that that happens. It's working for me now. I might take a look at a better solution later. 
Thanks for the help. I've been moving from OneNote to QOwnNotes for work lately. It's been great. I love the fact that there's a nice integration with nextcloud and it works well on the phone. 
Your responses here were also super fast. Keep it up. Great work!

**Comment by pbek** [comment]
Thank you. 😁 

Btw. this this block still doesn't render:

    ```mermaid
    graph TB
        subgraph Your computer
            qon((QOwnNotes))-->md{{"Markdown files"}}
            sync("Nextcloud Sync")-->md
            qon-comp("QOwnNotes browser extension")-->qon
        end
        subgraph Your Nextcloud server
            qon-api("QOwnNotesApi")-->ncs[("Nextcloud server")]
            nc-notes-app("Nextcloud Notes")-->ncs
        end
    
        nc-notes-mob("Nextcloud Notes mobile app")-->nc-notes-app
        qon-web-app("QOwnNotes web application")-->qon
        qon-->qon-api
        qon-->ncs
        sync-->ncs
        qon-.->qon-web-api("api.qownnotes.org")
        qon-web-api-->github("GitHub")
    ```

**Comment by cyclops1982** [comment]
https://github.com/qownnotes/scripts/pull/146 :-)

**Comment by pbek** [comment]
I can confirm, it now works, thank you!

**Pull request merged**
