### PR TITLE
Added Ascii Tree Factory

### PR DESCRIPTION
**Pull request by 77nnit**
Added new script `ASCII-Tree-Factory`

### CODE REVIEW

**Comment by pbek** [comment]
> https://github.com/qownnotes/scripts/actions/runs/11615257414/job/32349474963?pr=243#step:3:6

Please make the identifier lowercase.

**Comment by pbek** [comment]
Please ping me when you are done.

**Comment by 77nnit** [comment]
> Please ping me when you are done.

Done.

**Comment by pbek** [comment]
Thank you for your contribution!

**Pull request merged**
