### PR TITLE
Added features to export-notes-as-website

### PR DESCRIPTION
**Pull request by bvn9ne**
I tested it and it seems to work fine. If you find there is an issue, let me know so I can fix it asap.

### CODE REVIEW

**Comment by pbek** [comment]
What happens if someone updates the script and has no folder set?

**Comment by pbek** [comment]
Don't you need to update the wiki as well to introduce the new feature?

**Comment by bvn9ne** [comment]
I can make the change that if the folder is empty it defaults to old behavior. As for the wiki, I don't mind updating it, it just seemed premature to update it before the change was accepted.

**Comment by bvn9ne** [comment]
It should now default to old behavior (saving in subfolder of notes) if defaultExportPath is empty. It should also default to "export" if old behavior is used and defaultExportFolder is empty.

**Comment by pbek** [comment]
Thank you. I'll change the rest myself.

**Comment by pbek** [comment]
I updated the readme text, the version number and the authors.

**Pull request merged**
