### PR TITLE
Script for unwrapping paragraphs into single lines

### PR DESCRIPTION
**Pull request by clintonthegeek**
Thought I'd try scratching my own itch this time! And even put the files in the right spot. :)

I'm often copy/pasting text out of PDFs which come with original line-breaks straight from the book. Instead of manually editing them line by line, this script will automatically unwrap any selected series of lines into one large line, allowing the user to select paragraphs and turn their hard-coded word-wrapping over to the dynamic word-wrapping of QOwnNotes.

### CODE REVIEW

**Comment by pbek** [comment]
```
$ php run-tests.php
Directory 'unWrap'
  Invalid charactes were found in identifier 'unWrap'!
```

please use only lowercase character

**Comment by pbek** [comment]
> please use only lowercase character

best also for the folder name

**Comment by clintonthegeek** [comment]
Okay, done!

**Comment by pbek** [comment]
Great, thank you!

**Pull request merged**
