### PR TITLE
Aganel's Windows patch for Latex Math

### PR DESCRIPTION
**Pull request by Aganel**
Fixed image generation and display of TeX formula preview (Latex Math) for Windows platform.
Removed unused code (import QtQuick, local fileExists, execBash)

I tried to make little to none changes on the linux "side" of the code, but one has to test it on Linux platform to be sure it's ok.

### CODE REVIEW

**Comment by pbek** [comment]
@Aganel, looks nice. Have you tested the script on the other two operating system (at least Linux).
@r00tr4v3n, does this look ok for you?

**Comment by pbek** [comment]
@Aganel 
Can you please also bump the version number in the `info.json` so users will get an update notification and add yourself as author.

**Comment by Aganel** [comment]
Hello again! There were some problems with my github notifications, sorry for delay. I edited info.json 

> 
> 
> @Aganel
> Can you please also bump the version number in the `info.json` so users will get an update notification and add yourself as author.

**Comment by pbek** [comment]
Thank you, can you please write `@Aganel` instead of `Aganel` as username. 😉

**Comment by Aganel** [comment]
> 
> 
> Thank you, can you please write `@Aganel` instead of `Aganel` as username. wink

Done )

**Pull request merged**
