### PR TITLE
add restructuredtext v0.0.1.

### PR DESCRIPTION
**Pull request by zaazbb**
I add a reStructuredText support script. I'm pleased to share with others. :)

### CODE REVIEW

**Comment by pbek** [comment]
Nice!

>   Script 'restructuredtext' doesn't exist!

You need to write `restructuredtext.qml` in your `info.json`. And please bump the `minAppVersion`, I don't think `noteToMarkdownHtmlHook` existed back then. 😉

**Comment by pbek** [comment]
> reStructuredText support script

Can you please describe in more detail what the script is supposed to do and how to use it.

**Comment by pbek** [comment]
> "platforms": ["linux", "macos", "windows"],

Are you sure this works also on Windows? I can see a `"python", ["-c", "import docutils.core;\`. I guess for it to work on Windows there needs to be a setting where the python binary sits...

**Comment by pbek** [comment]
Thank you!

> Are you sure this works also on Windows? I can see a "python", ["-c", "import docutils.core;\. I guess for it to work on Windows there needs to be a setting where the python binary sits...

Do you want to remove the windows support or do you want to add a setting for the python binary (like for example here: https://github.com/qownnotes/scripts/blob/master/merge-notes/merge-notes.qml)?

**Comment by zaazbb** [comment]
This script can preview and help format reStructuredText style note.<br/><br/><b>Dependencies</b><br/><a href="https://docutils.sourceforge.io/rst.html">docutils</a><br/><br/><b>Usage</b><br/>1. Install dependencies.<br/>(1). Install <a href="https://www.python.org">python3</a>.<br/>(2). Install <a href="https://docutils.sourceforge.io/rst.html">docutils</a>: <code>pip3 install docutils docutils</code><br/>(3). Install <a href="https://pygments.org">pygments</a>: <code>pip3 install docutils pygments</code> (if you need code highlight)<br/><br/>2. Change default note file extension to rst.(Settings > General)<br/><br/>3. New a rst extension note file, and edit it using custom actions toolbar/menu added by this script.<br/><br/><b>Note</b><br/>You can use <b>bold</b> and <b>italic</b> buildin formating buttons directly, because reStructuredText have the same bold/italic format as Markdown .<br/><br/>You\'d better use <b>dark</b> theme, because code highlight using darcula theme now.(Enable dark mode in Setting > Interface , and select dark color schema in Setting > Editor > Editor font & colors)

**Todo**
 - add reStructuredText keyword highlight and autocomplete.
 - reuse buildin formating buttons? Maybe need more new QOwnNotes script  methods/hooks helping to do it.
 - add reStructuredText table more other formating actions.
 - and reStructuredText Directive templates.
 - note head use reStructuredText style Title.

**Comment by zaazbb** [comment]
> > "platforms": ["linux", "macos", "windows"],
> 
> Are you sure this works also on Windows? I can see a `"python", ["-c", "import docutils.core;\`. I guess for it to work on Windows there needs to be a setting where the python binary sits...

I test on windows 10, it works. python.exe path added to path when installing by default.

**Comment by zaazbb** [comment]
> Thank you!
> 
> > Are you sure this works also on Windows? I can see a "python", ["-c", "import docutils.core;. I guess for it to work on Windows there needs to be a setting where the python binary sits...
> 
> Do you want to remove the windows support or do you want to add a setting for the python binary (like for example here: https://github.com/qownnotes/scripts/blob/master/merge-notes/merge-notes.qml)?

I'll add some settings on future, like [merge-notes](https://github.com/qownnotes/scripts/tree/master/merge-notes), if it is needed.

**Comment by pbek** [comment]
> I'll add some settings on future, like merge-notes, if it is needed.

ok. there are just a few lines of code to add to the script 😉

**Pull request merged**
