### PR TITLE
Html hook update

### PR DESCRIPTION
**Pull request by r00tr4v3n**

### CODE REVIEW

**Comment by pbek** [comment]
It generally would be better to put whitespace fixes in a different PR, since they are producing a lot of changes...

**Comment by pbek** [comment]
Can you please raise the `minAppVersion` to 20.6.0 in all scripts you updated.

**Comment by pbek** [comment]
Otherwise it looks fine, thanks a lot.

**Comment by r00tr4v3n** [comment]
> It generally would be better to put whitespace fixes in a different PR, since they are producing a lot of changes...

Sorry, I didn't notice `bautify` changed so much in the background.

**Comment by pbek** [comment]
> Sorry, I didn't notice bautify changed so much in the background.

no worries :grin: 

Thank you, I will merge it after the release.

**Pull request merged**
