### PR TITLE
New script that allows for importing/exporting notes from Vivaldi

### PR DESCRIPTION
**Pull request by fnkabit**
Feature: https://github.com/pbek/QOwnNotes/issues/1165
Video demo: https://www.youtube.com/watch?v=lmccLlUt64g

Currently allows for importing notes only.

### CODE REVIEW

**Comment by pbek** [comment]
Awesome! Thank you for the contribution!

**Comment by fnkabit** [comment]
Thank you !

**Comment by RealDrJester** [comment]
Nice!! Thank you! Suggestion: Make it so it can import each folder and follow the vivaldi hierarchy. For instance: 

Folder 1
|
|
+- Sub-Folder 1
      |
      |
      + Sub-Sub-Folder 1
Folder 2
|
|
+- Sub-Folder 2
      |
      |
      + Sub-Sub-Folder 2

**Comment by fnkabit** [comment]
Thank you @RealDrJester .
Did you encounter issues with the import script not following the folder hierarchy in your Vivaldi notes ?
As long as you have 'Use note subfolders' checked for your current folder, it should follow the Vivaldi folder hierarchy (like showed in the demo), otherwise it means that I might have made a mistake.

**Comment by RealDrJester** [comment]
I just had the time to check this out now. Yep, checking the "Use Note Subfolders" seems to work, probably a problem between the keyboard and the chair here. haha


It is also asking for me to create Folders, and using UUID as note titles, instead of the actual title of the note.


I'm currently cleaning up the notes, as one of the syncs from Vivaldi, it created hundreds of copies of some notes. So it should decrease the time it takes to import.

**Comment by RealDrJester** [comment]
Here's what I found out. At least, partially, because I had to close it in the middle of importing since I had to sleep. 

The notes are importing like this. I wanted to send you the whole file, but I have a lot of personal notes in there. :/ 

This is what it looks like in Vivaldi:
```
Folder 1
|
|
+- Sub-Folder 1
      |
      |
      + Sub-Sub-Folder 1
          + Note 1
          + Another Note 1
Folder 2
|
|
+- Sub-Folder 2
      |
      |
      + Sub-Sub-Folder 2
          + Note 2
          + Another Note 2
Folder 3
|
|
+- Sub-Folder 3
      |
      |
      + Sub-Sub-Folder 3
          + Note 3
          + Another Note 3
```

After importing(I believe, based on the file size in my disk, and the note, around 50% was done):

```
Folder 1
|
|
+- Sub-Folder 1
      |
      |
      + Sub-Sub-Folder 1
          + Note 1
          + Another Note 1
Folder 2
|
|
+- Sub-Folder 2
     |
     |
     + Sub-Sub-Folder 2
     + Note 2
     + Another Note 2
     + Folder 3
     + Sub-Folder 3
     + Sub-Sub-Folder 3
     + Note 3
     + Another Note 3
```

**Comment by fnkabit** [comment]
Thank you @RealDrJester ; I will create a Vivaldi note structure similar to yours and try to reproduce the issue.

**Comment by RealDrJester** [comment]
> Thank you @RealDrJester ; I will create a Vivaldi note structure similar to yours and try to reproduce the issue.

I wish I could help you, but I have the coding skills of a monkey high on meth. I've added a couple of screenshots to show some of the problems. Hope this is more helpful than just random text. 

Screenshot 2020-10-30 025549
Screenshot 2020-10-29 212431

**Pull request merged**
