### PR TITLE
Backlinks update: fix for Windows 

### LINKED ISSUE #231: [BUG] Backlinks on Windows
#### Script name
backlinks

#### Script authors
@dohliam 

#### Expected behavior
Works on Windows like on Linux.

#### Actual behavior
Does not find any backlinks on Windows, and when finding them clicking on them does not work.

#### Fix diff
I hope this is clear.
```
@@ -25,13 +25,6 @@
         }
     ];
 
-    function getSubFolder(note, path) {
-        var fileName = note.fullNoteFilePath;
-        var pathRe = new RegExp(path + dirSep + "((.*)" + dirSep + ")*.*");
-        var subfolderName = fileName.replace(pathRe, "$2");
-        return subfolderName;
-    }
-
     function normalizeText(text) {
         return text.toLowerCase().replace(/[\-\s_]/g, "").replace(/\[\[([^\]]+)\|[^\]]+\]\]/g, "[[$1]]");
     }
@@ -52,6 +45,9 @@
             out += "<h2>Backlinks</h2>\n\n<ul>\n";
             for (var i = 0; i < backlinks.length; i++) {
                 var backlinkPath = backlinks[i]["p"];
+                if (script.platformIsWindows()) {
+                    backlinkPath = "/" + backlinkPath;
+                }
                 var backlinkTitle = backlinks[i]["t"];
                 out += "    <li><a href=\"file://" + backlinkPath + "\" title=\"" + backlinkPath + "\">" + backlinkTitle + "</a></li>\n";
             }
@@ -62,9 +58,12 @@
 
     function getBacklinks(note) {
         var noteName = note.name;
-        var path = script.currentNoteFolderPath();
-        var subfolderName = getSubFolder(note, path);
+        var subfolderName = note.relativeNoteFileDirPath;
         var nameNormalized = normalizeText(noteName);
+        /* Does not work on Windows
+        dirSep = script.dirSeparator();
+        */
+        dirSep = "\/";
 
         var noteIds = script.fetchNoteIdsByNoteTextPart("");
         var backlinks = [];
@@ -72,7 +71,7 @@
         noteIds.forEach(function (pageId){
             var pageObj = script.fetchNoteById(pageId);
             var basename = pageObj.name;
-            var pageGroup = getSubFolder(pageObj, path);
+            var pageGroup = pageObj.relativeNoteFileDirPath;
             var text = pageObj.noteText;
             if (/\[\[.*\]\]/.test(text)) {
                 var normalizedText = normalizeText(text);
```

#### Additional context
Note that the paths in Windows within QOwnnotes also use "/" as separator.

Function getSubFolder is no longer required, replaced with built-in functions.

I have to disable "Convert linked filenames to lower case" on Windows for the wikilinks script, otherwise the links don't work.

### PR DESCRIPTION
**Pull request by Ultra2D**
Fixes #231 .

### CODE REVIEW

**Comment by pbek** [comment]
@dohliam

**Comment by pbek** [comment]
Maybe add yourself as maintainer, @Ultra2D.

**Comment by dohliam** [comment]
@Ultra2D Looks like I missed the original notification, sorry about that! I don't have a Windows machine to test this on, but the updated script seems to be working fine on Linux (tried with both ATX and Setext-style headings). So everything looks good from my end. :+1:

**Comment by Ultra2D** [comment]
> Maybe add yourself as maintainer, @Ultra2D.

Thanks, it's not necessary. It was just a bug fix that made my life easier. Happy user of both the application and the script. Keep up the good work.

**Comment by pbek** [comment]
Thank you! Thank you for the fix! 😉

**Pull request merged**
