### PR TITLE
Adding a new handy script to select a whole section of a note

### PR DESCRIPTION
**Pull request by Beurt**

### CODE REVIEW

**Comment by pbek** [comment]
`select-section/info-select_section.json` needs be be called `select-section/info.json`

**Comment by Beurt** [comment]
Oh sorry ! I was distracted (I was in a train) while naming files.

**Comment by pbek** [comment]
Still some errors... 😉 
https://github.com/qownnotes/scripts/actions/runs/4095774356/jobs/7062935246

**Comment by Beurt** [comment]
> Still some errors... wink https://github.com/qownnotes/scripts/actions/runs/4095774356/jobs/7062935246

Sorry, I really need to be more focused on that PR!

(I just realized that my Ablocker hides error messages from Github CI, and I thought the messages were empty...)

**Comment by pbek** [comment]
> (I just realized that my Ablocker hides error messages from Github CI, and I thought the messages were empty...)

Interesting, I never had that. what do you use if I may ask?

**Comment by Beurt** [comment]
> Interesting, I never had that. what do you use if I may ask?

I use the very aggressive (but also efficient) uMatrix.

**Comment by pbek** [comment]
thank you... I'm still at uBlock :) (Plus pihole)

**Pull request merged**
