### PR TITLE
Convert selected CSV text to Markdown table

### PR DESCRIPTION
**Pull request by 77nnit**
The script converts a selected CSV text to a markdown table representation.

### CODE REVIEW

**Comment by 77nnit** [comment]
Bug on the "no headers" code branch. Retiring the pull request.

**Comment by pbek** [comment]
Just create a new PR then... 😉

Btw, did you see this dialog?

image

**Comment by 77nnit** [comment]
> Just create a new PR then... 😉
> 
> Btw, did you see this dialog?
> 
> image

My goodness! I really never had idea it was there! And I assumed it after seeking the script list. I couldn't believe nobody considered a CSV to MD table conversion.

My bad, now I need to think about another script... Any requests lately???

**Comment by pbek** [comment]
No itch to scratch? 😁

There are some open issues at https://github.com/qownnotes/scripts/issues?q=is%3Aopen+is%3Aissue and probably lots that have gone stale at https://github.com/qownnotes/scripts/issues?q=is%3Aclosed+label%3AStale+ 😉

**Pull request closed without merging**
