### PR TITLE
Added Taskwarrior import/export script.

### PR DESCRIPTION
**Pull request by fmakowski**
Hi!

Decided to test out scripting possibilities by writing this short script. The main goal is to take a list and create task entries in Taskwarrior that reflect list items.

For example: if the text is:

    project: projectName1
    
    * description of first task
    * description of second

    project: projectName1.nested

    * some other task description

    project: projectName2

    * another

Then the resulting shell calls are:

    task add pro:projectName1 description of first task
    task add pro:projectName1 description of second
    task add pro:projectName1.nested some other task description
    task add pro:projectName2 another

As you can see, there are various ways of optimizing this method, and I will work on that to make it more useful. Also, this is one of many steps to somehow integrate Taskwarrior into QOwnNotes, as I use both and would love to see it closer someday.

Best regards!
Filip

BTW. I have implemented "export" option only as of now, but "import" will be there soon. Another pull request I presume ;)

### CODE REVIEW

**Comment by Maboroshy** [comment]
Can't test the script, but there's a thing I don't understand. You make new line handling based on OS, Windows vs Unix-like. Yet there's no difference for OS in `startDetachedProcess`, it's fixed path. 

I've looked to Taskwarrior web site, and looks like it's Unix-like only, it uses Cygwin or WSL for Windows. 

Will Windows handle path set in `startDetachedProcess`?

**Comment by fmakowski** [comment]
@Maboroshy you are absolutely right, I have forgot about that. I don't think Windows can handle that path, and the main problem is, I am not sure if Windows can natively run Taskwarrior in the first place (although I am using it on Windows 10 from Ubuntu bash, but that is completely different story).

Do you think it makes sense to prepare a disclaimer like "Unix-like OSes only!" or rather make some way of parametrizing the script (like, settings in the Scripts window)? Even if you install Taskwarrior with Cygwin, the path may vary depending on the user preferences.

**Comment by Maboroshy** [comment]
"Unix only" disclaimer is a short way, but implementing settings will possibly enable more people to use the script.

**Comment by fmakowski** [comment]
That is quite true. I have commited changes to the description parameter, where I have temporarily added "Unix-only" statement. Still, I will try to make it in a way, where it can be used properly in Windows. I have not removed the `\r\n` check though.

**Pull request merged**
