### PR TITLE
Script to use Critic Markup in QownNotes

### PR DESCRIPTION
**Pull request by Beurt**
Initial PR of a new script to add Critic Markup support to QownNotes. [Critic Markup](http://criticmarkup.com/) is intended to show edit marks and annotations on Markdown text.

This preliminary implementation adds buttons to the toolbar, and adds support for conversion from the markup to HTML according to [Critic Markup specification](http://criticmarkup.com/spec.php).

Unfortunately I don't have a clue on how to implement markup coloration on the editor side.

You can experiment with the provided example :

```
Don't go around saying{-- to people that--} the world owes you a living. The world owes you nothing. It was here first. {~~One~>Only one~~} thing is impossible for God: To find {++any++} sense in any copyright law on the planet. {==Truth is stranger than fiction==}{>>strange but true<<}, but it is because Fiction is obliged to stick to possibilities; Truth isn't.

```

### CODE REVIEW

**Comment by pbek** [comment]
Thank you!

> Critic Markup is intended to show edit marks and annotations on Markdown text.

Interesting concept. Haven't seen that in the wild. In what circles is Critic Markup used?

> Unfortunately I don't have a clue on how to implement markup coloration on the editor side.

That can't be done in a script. It can only be implemented in QOwnNotes itself.

**Comment by Beurt** [comment]
> Thank you!
>

You're welcome!
 
> > Critic Markup is intended to show edit marks and annotations on Markdown text.
> 
> Interesting concept. Haven't seen that in the wild. In what circles is Critic Markup used?
> 

I really don't know. But I recently had the need for that (I was writing a scientific paper in QOwnNotes¹ and needed to annotate my work). So I made a quick (and dirty) implementation.

¹ Yes, I'm using QOwnNotes as my main text editor coupled with Pandoc, because QOwnNotes is currently the best Markdown editor I have tested (And I tested A LOT).

> > Unfortunately I don't have a clue on how to implement markup coloration on the editor side.
> 
> That can't be done in a script. It can only be implemented in QOwnNotes itself.

I see. That is too bad for such syntax enrichment.

**Comment by pbek** [comment]
> I really don't know. But I recently had the need for that (I was writing a scientific paper in QOwnNotes¹ and needed to annotate my work). So I made a quick (and dirty) implementation.

And I wonder who then did the accepting or rejecting? Another person? Can he/she handle the syntax too?

> ¹ Yes, I'm using QOwnNotes as my main text editor coupled with Pandoc, because QOwnNotes is currently the best Markdown editor I have tested (And I tested A LOT).

Oh, thank you. It was never intended to be a markdown editor. It's more like an IDE for note taking with markdown. 😁 

> I see. That is too bad for such syntax enrichment.

Would be hard to implement, the highlighting got very complex already. You can make a feature request on https://github.com/pbek/QOwnNotes/issues to discuss with @Waqar144, but even if implemented highlighting done in the script engine would have side effects with code blocks and the like...

**Comment by Beurt** [comment]
> And I wonder who then did the accepting or rejecting? Another person? Can he/she handle the syntax too?
>

In that case that was me and... me :smile: . Just wanting to edit my own text with various comments before making big changes.
 
> Oh, thank you. It was never intended to be a markdown editor. It's more like an IDE for note taking with markdown. grin
>

Not intended, maybe! But it is certainly a very handful IDE for all kind of Markdown(ish) productions.

Bravo!
> 
> Would be hard to implement, the highlighting got very complex already. You can make a feature request on https://github.com/pbek/QOwnNotes/issues to discuss with @Waqar144, but even if implemented highlighting done in the script engine would have side effects with code blocks and the like...

Don't give to this any kind of priority!

**Comment by pbek** [comment]
> Just wanting to edit my own text with various comments before making big changes.

I was hoping there are technically versed publisher's reader out there 😅 

> Not intended, maybe! But it is certainly a very handful IDE for all kind of Markdown(ish) productions.

A lot of features were added to make it versatile in many ways. 😅  (there a people who say: too many features) 😆 

> Don't give to this any kind of priority!

Like I said, it would be interesting to discuss...

**Comment by Waqar144** [comment]
> > And I wonder who then did the accepting or rejecting? Another person? Can he/she handle the syntax too?
> 
> In that case that was me and... me 😄 . Just wanting to edit my own text with various comments before making big changes.
> 
> > Oh, thank you. It was never intended to be a markdown editor. It's more like an IDE for note taking with markdown. grin
> 
> Not intended, maybe! But it is certainly a very handful IDE for all kind of Markdown(ish) productions.
> 
> Bravo!
> 
> > Would be hard to implement, the highlighting got very complex already. You can make a feature request on https://github.com/pbek/QOwnNotes/issues to discuss with @Waqar144, but even if implemented highlighting done in the script engine would have side effects with code blocks and the like...
> 
> Don't give to this any kind of priority!

Sure thing, open an issue and we can discuss what needs to be done.

**Pull request merged**
