### PR TITLE
Added scripts: categorized-notes, file-export, yaml-nested-tags

### PR DESCRIPTION
**Pull request by r00tr4v3n**
A few scripts as promised @pbek 

### Categorized notes
- based on meeting-notes
- creates a UI box to select a category and creates a note in a subfolder

### File export
- allows export of attachments and media by selecting them
- allows text formatting for attachments
- automatically zips multiple files (Linux only for now)

### YAML nested tags
- nested tags inside a YAML header

### CODE REVIEW

**Comment by pbek** [comment]
These look like great scripts! I even saw that you are loading an external qml, I wonder if that works on all platforms. Currently I can't test it yet, because `categorized-notes-window.qml` will not be distributed if you don't reference it in the `info.json`, see: https://github.com/qownnotes/scripts/blob/594f4d9b0800ca057e605fc1afa8329c77764090/markdown-it/info.json#L5

Currently there is an error like `[20:00:07] [critical] file:///home/omega/.local/share/PBE/QOwnNotesDebug/scripts/categorized-notes/categorized-notes-window.qml:-1 No such file or directory `

**Comment by pbek** [comment]
I fixed it for you.

**Comment by r00tr4v3n** [comment]
Good to know, thank you!
Yes, I like UIs to speed up the daily workflow :)

**Comment by pbek** [comment]
And the qml user interface really works, impressive!
your "YAML nested tags" script also works great (you could have removed the hooks with debug messages only)

**Comment by r00tr4v3n** [comment]
Whoops, I must have forgot about those when trying to fix the header/filename issue that never existed :wink:

**Comment by phdfloppa** [comment]
How do I use the Categorized Notes script? The script says it creates a menu item and a button, but I can't find either.

**Comment by phdfloppa** [comment]
Are you talking about Window --> Toolbars --> Show custom action toolbar? If so, then yes, but I still dont see anything

**Pull request merged**
